### ISSUE TITLE
当NSArray内只有一个对象的时候无法捕获objectAtIndex:越界访问

### ISSUE THREAD

**Issue by unkosun** [chenfanfang/AvoidCrash#1]
当NSArray内只有一个对象的时候，它的真正类型是 __NSSingleObjectArrayI，不是__NSArrayI。

**Comment by chenfanfang** [comment]
好的，谢谢提醒。到时候我修复下里面的BUG

**Comment by chenfanfang** [comment]
不知 NSDictionary只有一个键值对是，真正类是什么类。到时候有待去排查下

**Comment by unkosun** [comment]
只有一个键值对的字典，真正类型是__NSSingleEntryDictionaryI，还有对于count = 0的数组 真正类型 是 __NSArray0，同样 字典是__NSDictionary0，都需要处理下
