### ISSUE TITLE
为什么string 追加字符串不成功

### ISSUE THREAD

**Issue by kedu** [chenfanfang/AvoidCrash#15]
///
        [AvoidCrash exchangeClassMethod:stringClass method1Sel:@selector(stringByAppendingString:) method2Sel:@selector(avoidCrashStringByAppendingString:)];

//
-(NSString*)avoidCrashStringByAppendingString:(NSString*)string{

    NSString *newStr = nil;
    
    if (string==nil) {
        string=@"";
    }
    
    @try {
        
        newStr = [self avoidCrashStringByAppendingString:string];
    }
    @catch (NSException *exception) {
        
        NSString *defaultToDo = AvoidCrashDefaultReturnNil;
        
        [AvoidCrash noteErrorWithException:exception defaultToDo:defaultToDo];
        
        newStr = nil;
    }
    @finally {
        return newStr;
    }

}

**Comment by chenfanfang** [comment]
你好，你能否将你遇到的问题描述清楚下

**Comment by kedu** [comment]
因为你的没string的StringByAppendingString这个方法.我就照着你的模式写了一个,发现不起作用.

**Comment by chenfanfang** [comment]
下面的代码你参考下，作用在NSString中


- (NSString *)avoidCrashStringByAppendingString:(NSString *)aString {
    NSString *str = self;
    @try {
        str = [self avoidCrashStringByAppendingString:aString];
    } @catch (NSException *exception) {
        NSString *defaultToDo = AvoidCrashDefaultIgnore;
        [AvoidCrash noteErrorWithException:exception defaultToDo:defaultToDo];
    } @finally {
        return str;
    }
}
