### ISSUE TITLE
与Reactivecocoa冲突

### ISSUE THREAD

**Issue by atony2099** [chenfanfang/AvoidCrash#17]
我的项目中已经用pods集成了RAC,手动导入AvoidCrash时候，可以正常运行，但是一旦对 NSMutableArray+AvoidCrash.m 文件进行 -fno-objc-arc 设置的时候，rac文件立即报错 

      /Pods/ReactiveObjC/ReactiveObjC/NSObject+RACKVOWrapper.h:36:113: Cannot create __weak reference in file using manual reference counting

**Comment by chenfanfang** [comment]
你好，我这里没发现和Reactivecocoa有冲突，麻烦你新建一个项目，同时将Reactivecocoa和AvoidCrash都集成到新项目中，看下是否可以重现问题。
