### ISSUE TITLE
上线项目AvoidCrash 交换方法 NSString出现多处crash 

### ISSUE THREAD

**Issue by Mars-Programer** [chenfanfang/AvoidCrash#19]
<img width="1421" alt="2017-08-02 11 47 14" src="https://user-images.githubusercontent.com/16496337/28856891-20fd0d60-7778-11e7-8915-f1bad29343dd.png">

项目上线后使用 NSString 从xcode crash跟踪发现出现很多这里的crash

**Comment by Mars-Programer** [comment]
<img width="1420" alt="2017-08-02 11 48 26" src="https://user-images.githubusercontent.com/16496337/28856925-55f59b68-7778-11e7-84ef-0bee8c53e959.png">

**Comment by chenfanfang** [comment]
你好，app运行中，能否重现crash ?

**Comment by chenfanfang** [comment]
@Mars-Programer

**Comment by Mars-Programer** [comment]
嗯呢 你好 我这里运行debug 没有复现 但是我在Xcode crash跟踪里发现了170多个错误都是这里的
<img width="936" alt="2017-08-02 1 13 59" src="https://user-images.githubusercontent.com/16496337/28858597-438e1e94-7784-11e7-9b6f-69bb569aedc4.png">

**Comment by Mars-Programer** [comment]
所以我们可能要做一些猜测 这里什么情况下会发生crash现象 class类型不匹配吗

**Comment by Mars-Programer** [comment]
@chenfanfang

**Comment by chenfanfang** [comment]
1、麻烦换成release模式试下，看是否能重现。 
2、线上app下载下来看下，看是否可以重现。  
3、测试机用10以上的系统

**Comment by Mars-Programer** [comment]
好的 我先试试 有结果issue你

**Comment by Mars-Programer** [comment]
你好 打扰了 我用错误的代码测试过 并没有发现crash的原因 
我猜想会不会是 AvoidCrash 虽然拦截了crash 并@try catch 但是这个异常还是会被监测到 并且Xcode 会跟踪到 其实并没有真正crash呢
你怎么看呢
