### ISSUE TITLE
更新到2.2.2beta 有一个疑问

### ISSUE THREAD

**Issue by Mars-Programer** [chenfanfang/AvoidCrash#20]
<img width="1061" alt="2017-08-03 11 49 13" src="https://user-images.githubusercontent.com/16496337/28905117-b32cf5a0-7841-11e7-9616-2180c6070ea4.png">
在方法内调用自己的方法 这里不会造成死循环吗 @chenfanfang

**Comment by chenfanfang** [comment]
@Mars-Programer 方法已经交换了，调用了自己---->其实是调用了与之替换了的那个方法

**Comment by chenfanfang** [comment]
不会造成死循环
