### ISSUE TITLE
最新版版本的unrecognized selector sent to instance 会造成crash

### ISSUE THREAD

**Issue by Mars-Programer** [chenfanfang/AvoidCrash#23]
开启makeAllEffective 后 两次crash 的log 
<img width="605" alt="2017-08-09 5 32 12" src="https://user-images.githubusercontent.com/16496337/29115422-3b277010-7d2a-11e7-94d3-ea15acf356a0.png">
<img width="1017" alt="2017-08-09 5 36 04" src="https://user-images.githubusercontent.com/16496337/29115426-3c30e6b2-7d2a-11e7-930b-0ec0e5bf33d5.png">
开启后点击textView输入时必现 
（环境 ： Xcode8  模拟器）

**Comment by chenfanfang** [comment]
谢谢反馈，现在针对unrecognized selector sent to instance 异常的捕获，全部交个使用者来处理了，具体要防止哪些类的方法的unrecognized selector sent to instance崩溃，就需要自己手动添加，具体请查看AvoidCrash.h中的介绍
