### ISSUE TITLE
友盟统计无法获取到错误信息

### ISSUE THREAD

**Issue by jinlongzhu** [chenfanfang/AvoidCrash#24]
集成此功能后 友盟统计无法获取到崩溃消息统计

**Comment by chenfanfang** [comment]
你好，只要被AvoidCrash捕获到的异常，就不会导致崩溃，友盟自然无法记录到崩溃信息，但是AvoidCrash提供了具体崩溃信息，你可以上传自定义的异常(你需要查看下友盟是否有上传自定义异常的方法，腾讯的bugly有上传自定义异常的功能)。具体你可以看下Demo中的AppDelegate里面的介绍
