### ISSUE TITLE
EXC_BAD_ACCESS 问题

### ISSUE THREAD

**Issue by lixiang1994** [chenfanfang/AvoidCrash#25]
崩溃在这里

<img width="1400" alt="1111222" src="https://user-images.githubusercontent.com/13112992/29611728-46e6bafc-8831-11e7-8167-b83e9311a713.png">

这时主线程在这里

<img width="1400" alt="222333" src="https://user-images.githubusercontent.com/13112992/29611789-8cabf4bc-8831-11e7-9890-a2a3bdd79dac.png">

运行环境 iPhone4s  iOS8.1  debug 
频率 偶现

**Comment by JasonLxj** [comment]
这个是死循环了啊，线程11

**Comment by kobe1941** [comment]
@lixiang1994 试试FFExtension 😳
