### ISSUE TITLE
弹出键盘时崩溃

### ISSUE THREAD

**Issue by wzhios** [chenfanfang/AvoidCrash#28]
当使用makeAllEffective时，弹出键盘会crash,当使用becomeEffective时，是没问题的，键盘正常弹出。（备注：我这里使用了IQKeyboardManager）

**Comment by chenfanfang** [comment]
@wzhios 请更新到 最新版本  pod 'AvoidCrash', '~> 2.3.0-beta'

**Comment by wzhios** [comment]
恩 试过了 可以的
