### ISSUE TITLE
在iOS 11中好几个都不能用了

### ISSUE THREAD

**Issue by jiliuliu** [chenfanfang/AvoidCrash#29]
下载demo运行了，ViewController中多个测试方法会崩溃

**Comment by 287291867** [comment]
xcode9上运行，也没用了，越界也检测不到了，怎么解决

**Comment by 287291867** [comment]
iOS 11可变数组失效，你可以这样改下试试，iOS 11以前方法是[__NSArrayM objectAtIndex:]，iOS 11以后方法是[__NSArrayM objectAtIndexedSubscript:]，所以把NSMutableArray+AvoidCrash.m文件中的24行代码中的objectAtIndex方法替换成objectAtIndexedSubscript

**Comment by zhugongyuan** [comment]
从哪里可以查到[__NSArrayM objectAtIndex:]失效了，我看官方文档objectAtIndexedSubscript是ios6.0 都可以使用的啊 @287291867

**Comment by wen644** [comment]
arrary[i]这样取对象，iOS 11以前方法是[__NSArrayM objectAtIndex:]，iOS 11以后方法是[__NSArrayM objectAtIndexedSubscript:]，麻烦作者加上[__NSArrayI objectAtIndexedSubscript:]

**Comment by Wuou** [comment]
希望可以解决你的问题
            /* 数组count >= 2 */
            [self wo_instanceSwizzleMethodWithClass:__NSArrayI orginalMethod:@selector(objectAtIndex:) replaceMethod:@selector(wo_objectAtIndex:)];//[arr objectAtIndex:];
            
            [self wo_instanceSwizzleMethodWithClass:__NSArrayI orginalMethod:@selector(objectAtIndexedSubscript:) replaceMethod:@selector(wo_objectAtIndexedSubscript:)];//arr[];

**Comment by chenfanfang** [comment]
已更新  兼容 iOS11   pod 2.5.1
