### ISSUE TITLE
[arr objectAtIndex:100]无法捕获异常

### ISSUE THREAD

**Issue by unkosun** [chenfanfang/AvoidCrash#3]
hook objectAtIndexedSubscript可以解决下标访问的方式，但是直接调用[arr objectAtIndex:100]是无法捕获异常的。

**Comment by chenfanfang** [comment]
好的，谢谢提醒，有空我处理一下

**Comment by chenfanfang** [comment]
由于类簇的问题，暂时只能拦截  array[100]这种方式的crash,  给你带来的不便，说声抱歉
