### ISSUE TITLE
运行内存过高  闪退

### ISSUE THREAD

**Issue by lwk123qq** [chenfanfang/AvoidCrash#36]
加入AvoidCrash 后会出现这个情况，具体原因不不知道

**Comment by chenfanfang** [comment]
你好，谢谢反馈。若可以，您可以进行一些比较，观察加入AvoidCrash前的运行内存和加入AvoidCrash后的运行内存情况。

并且确保项目中是否存在过多的异常被AvoidCrash捕获，小部分的异常是会出现些许的内存泄漏，AvoidCrash首页的末尾处也进行了相关的截图说明
