### ISSUE TITLE
unrecognized selector sent to instance 这个监测  弹起键盘时   会冲突吧

### ISSUE THREAD

**Issue by Etermally** [chenfanfang/AvoidCrash#40]
[AvoidCrash makeAllEffective];
NSArray *noneSelClassStrings = @[@"NSObject"];
[AvoidCrash setupNoneSelClassStringsArr:noneSelClassStrings];
//监听通知:AvoidCrashNotification, 获取AvoidCrash捕获的崩溃日志的详细信息
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(dealwithCrashMessage:) name:AvoidCrashNotification object:nil];
当我这么写时候 我调起键盘时候 [[AppDelegate appDelegate].window addSubview:weakSelf.writeComment]; 会崩溃在这句话这，错误报：libc++abi.dylib: terminate_handler unexpectedly threw an exception 这是什么问题呢？

**Comment by Etermally** [comment]
大神  看看什么问题呗  求解决

**Comment by Wuou** [comment]
过滤掉啊 ， 也许对你有用👇：
    NSString *methodName = NSStringFromSelector(aSelector);
    if ([NSStringFromClass([self.objc class]) hasPrefix:@"_"] || [self.objc isKindOfClass:NSClassFromString(@"UITextInputController")] || [NSStringFromClass([self.objc class]) hasPrefix:@"UIKeyboard"] || [methodName isEqualToString:@"dealloc"]) {

        return nil;
    }

**Comment by Etermally** [comment]
这个判断写在哪？大佬

**Comment by Etermally** [comment]
我写@"NSObject"的原因是我本来想监测一下我的BaseModel  😁  既然不能写，那就不写NSObject     谢谢大佬的耐心解答，😘
