### ISSUE TITLE
老铁，iOS 11上NSArray_Test_ObjectAtIndex拦不住

### ISSUE THREAD

**Issue by 279961172** [chenfanfang/AvoidCrash#41]
__exceptionPreprocess + 171
objc_exception_throw + 48
_CFThrowFormattedException + 194
+[__NSArrayI allocWithZone:] + 0
-[ViewController NSArray_Test_ObjectAtIndex] + 133
-[ViewController viewDidLoad] + 73

**Comment by 279961172** [comment]
在NSArray,NSMutableArray,NSMutableDictionary中增加
objectAtIndexedSubscript：
avoidCrashObjectAtIndexedSubscript:
avoidCrashSetObject:forKeyedSubscript:
即可

**Comment by chenfanfang** [comment]
已更新，兼容iOS11
