### ISSUE TITLE
NSMutableDictionary Set nil Object will Crash.

### ISSUE THREAD

**Issue by givingjan** [chenfanfang/AvoidCrash#45]
您好，有個問題想請教：

這段被Comment掉好像導致了NSMutableDictionary Set nil Object還是會Crash
```objc
[AvoidCrash exchangeInstanceMethod:dictionaryM 
method1Sel:@selector(setObject:forKey:) 
method2Sel:@selector(avoidCrashSetObject:forKey:)];
```
如果把它還原就不會Crash了，想問這行這樣做是有什麼特別用意嗎？謝謝

**Comment by xiaobt** [comment]
我也遇到相同的问题了，为啥要屏蔽[AvoidCrash exchangeInstanceMethod:dictionaryM 
method1Sel:@selector(setObject:forKey:) 
method2Sel:@selector(avoidCrashSetObject:forKey:)]; ？？？？
