### ISSUE TITLE
在键盘弹起后，按home进入后台崩溃

### ISSUE THREAD

**Issue by lwk123qq** [chenfanfang/AvoidCrash#5]
[UIKeyboardLayoutStar release]: message sent to deallocated instance
没有任何提示，和那个durixKit奔溃原因类似

**Comment by chenfanfang** [comment]
你好，你所说的问题已经修复，若用cocoapods集成，请更新即可(1.6.1版本解决了这个问题)，若是手动拖入项目，请配置一下，具体看介绍
