### ISSUE TITLE
死循环导致项目奔溃

### ISSUE THREAD

**Issue by ChenDongnan** [chenfanfang/AvoidCrash#60]
<img width="569" alt="2018-06-14 12 30 23" src="https://user-images.githubusercontent.com/16209342/41391732-05490e7a-6fcf-11e8-8c5e-17a91d60bc88.png">
你好，使用过程中发现会出现如图所示的情况导致崩溃，请问是什么原因呢？

**Comment by kobe1941** [comment]
我在写自己的库的时候也遇到过一次，不过我的原因是字符串函数的处理边界条件没有弄好，修复起来还算容易。
