### ISSUE TITLE
死循环,卡在了启动页

### ISSUE THREAD

**Issue by CoderST** [chenfanfang/AvoidCrash#63]
大神您好,项目中集成了框架,发现这个问题不是必现的 请看截图,
[AvoidCrash becomeEffective]; 这个方法我也是放在程序启动的最前端,用的是 pod 'AvoidCrash', '~> 2.5.2'版本,希望能收到您的回复.
<img width="470" alt="9c8197c46d28fe5617c106c3be45d39b" src="https://user-images.githubusercontent.com/18069121/44799240-0cdcf580-ab79-11e8-9c74-6bc048337667.png">

<img width="942" alt="b24244c77c3a5b8da5db83469b0a4f30" src="https://user-images.githubusercontent.com/18069121/44799263-19f9e480-ab79-11e8-9258-41ed378ae9a7.png">

**Comment by luson1201** [comment]
我看了代码也感觉奇怪，这样的调用不是会死循环的吗

**Comment by luson1201** [comment]
但是实际使用中并没有什么问题

**Comment by Mr-yuwei** [comment]
> 但是实际使用中并没有什么问题

runtime把方法交换了

**Comment by jezzmemo** [comment]
@luson1201 @Mr-yuwei 
可以尝试https://github.com/jezzmemo/JJException
