### ISSUE TITLE
偶现的一个crash，但是不太确定是否是添加AvoidCrash导致

### ISSUE THREAD

**Issue by erduoniba** [chenfanfang/AvoidCrash#64]
0 CoreFoundation | ___NSI0 + 704
-- | --
1 CoreFoundation | -[NSInvocation getArgument:atIndex:] + 160
2 Foundation | __NSGetValueWithMethod + 200
3 Foundation | -[NSObject(NSKeyValueCoding) valueForKey:] + 264
4 AccessibilityUtilities | ___57-[NSObject(UIAccessibilitySafeCategory) safeValueForKey:]_block_invoke + 32
5 AccessibilityUtilities | -[NSObject(UIAccessibilitySafeCategory) _accessibilityPerformSafeValueKeyBlock:withKey:onClass:] + 92
6 AccessibilityUtilities | -[NSObject(UIAccessibilitySafeCategory) safeValueForKey:] + 216
7 UIKit | -[UIViewControllerAccessibility _accessibilityLoadAccessibilityInformation] + 156
8 UIAccessibility | -[UIAccessibilityInformationLoader _loadAccessibilityInformationOnMainThread:] + 960
9 Foundation | __NSFireTimer + 88
10 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
11 CoreFoundation | ___CFRunLoopDoTimer + 864
12 CoreFoundation | ___CFRunLoopDoTimers + 248
13 CoreFoundation | ___CFRunLoopRun + 2168
14 CoreFoundation | CFRunLoopRunSpecific + 552
15 GraphicsServices | GSEventRunModal + 100
16 UIKit | UIApplicationMain + 236
17 meiju-ios | main (main.m:14)
18 libdyld.dylib | _start + 4

**Comment by NullWorld** [comment]
-[NSInvocation setArgument:atIndex:]: index (2) out of bounds [-1, 1]

**Comment by erduoniba** [comment]
@NullWorld 
什么意思，是NSInvocation方法，使用index2越界了吗

**Comment by NullWorld** [comment]
> @NullWorld
> 什么意思，是NSInvocation方法，使用index2越界了吗

我的是因为调用相册的时候，avoidCrash 的方法里，找到了ms，继续去给avoidCrash添加方法执行。

**Comment by erduoniba** [comment]
> > @NullWorld
> > 什么意思，是NSInvocation方法，使用index2越界了吗
> 
> 我的是因为调用相册的时候，avoidCrash 的方法里，找到了ms，继续去给avoidCrash添加方法执行。

@NullWorld
调用相册的确会Crash，看源码发现这里NSObject+AvoidCrash.m 代码的确有问题，这个是修正后的代码：

`- (NSMethodSignature *)avoidCrashMethodSignatureForSelector:(SEL)aSelector {
    
    NSMethodSignature *ms = [self avoidCrashMethodSignatureForSelector:aSelector];
    
    BOOL flag = NO;
    if (ms == nil) {
        for (NSString *classStr in noneSelClassStrings) {
            if ([self isKindOfClass:NSClassFromString(classStr)]) {
                ms = [AvoidCrashStubProxy instanceMethodSignatureForSelector:@selector(proxyMethod)];
                flag = YES;
                break;
            }
        }

        if (flag == NO) {
            NSString *selfClass = NSStringFromClass([self class]);
            for (NSString *classStrPrefix in noneSelClassStringPrefixs) {
                if ([selfClass hasPrefix:classStrPrefix]) {
                    ms = [AvoidCrashStubProxy instanceMethodSignatureForSelector:@selector(proxyMethod)];
                }
            }
        }
    }

    return ms;
}`

@chenfanfang 是否更新一下这里的源码。

**Comment by stevenwuzheng** [comment]
我之前用了这个框架，和你一样很多用户一启动就崩溃，影响真的很恶劣，bugly崩溃日志和你一样

**Comment by kevenleung** [comment]
新版的iOS13在部分手机上会产生这样的闪退，但自己的多个手机都没问题（相册，webKit、系统截屏都会闪退），注释掉就可以了。希望大神能修复一下。

**Comment by xuchengcheng** [comment]
具体是iOS 13，iphone 11 特定的系统和机型下，对NSNull 不存在的方法保护，没有保护住。不是这个库的问题，是代码中真的存在crash。

**Comment by openingax** [comment]
遇到同样的闪退问题，移除 AvoidCrash 后正常了，只有特定手机才会闪退，同型号同系统的不一定闪退。
