### ISSUE TITLE
启动崩溃 ！！！

### ISSUE THREAD

**Issue by LeeWongSnail** [chenfanfang/AvoidCrash#66]
0 CoreFoundation | ___NSI0 + 708
1 CoreFoundation | -[NSInvocation getArgument:atIndex:] + 160
2 Foundation | __NSGetValueWithMethod + 200
3 Foundation | -[NSObject(NSKeyValueCoding) valueForKey:] + 264
4 AccessibilityUtilities | ___57-[NSObject(UIAccessibilitySafeCategory) safeValueForKey:]_block_invoke +32
5 AccessibilityUtilities | -[NSObject(UIAccessibilitySafeCategory) _accessibilityPerformSafeValueKeyBlock:withKey:onClass:] + 64
6 AccessibilityUtilities | -[NSObject(UIAccessibilitySafeCategory) safeValueForKey:] + 200
7 UIKit | -[UIKeyboardLayoutStar clearHandwritingStrokesIfNeededAndNotify:] + 28
8 UIKit | -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1572
9 libdispatch.dylib | __dispatch_call_block_and_release + 24
10 libdispatch.dylib | __dispatch_client_callout + 16
11 libdispatch.dylib | _dispatch_main_queue_callback_4CF + 996
12 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
13 CoreFoundation | ___CFRunLoopRun + 1572
14 CoreFoundation | CFRunLoopRunSpecific + 424
15 GraphicsServices | GSEventRunModal + 100
16 UIKit | UIApplicationMain + 208
17 UXLive | main (main.m:14)
18 libdyld.dylib | _start + 4

**Comment by stevenwuzheng** [comment]
我之前用了这个框架，和你一样很多用户一启动就崩溃，影响真的很恶劣，bugly崩溃日志和你一，有没有什么办法可以解决啊

**Comment by kobe1941** [comment]
其实我想说try-catch的放崩溃方案，一旦出了问题，你是不好判断问题的出处的。所以我才重新写一个库...

**Comment by keepJion** [comment]
这个防崩溃的框架还是有点坑，线上崩溃率上升了不少。基本定位不到闪退的地方！

**Comment by kobe1941** [comment]
@keepJion 你可以用我写的那个试试，我们线上已经用上了，遇到的坑都解决了，现在运行良好。

**Comment by MasterBetter** [comment]
@kobe1941  你能否给我发下你写的那个，564811383@qq.com

**Comment by kobe1941** [comment]
@MasterBetter 点开个人主页就可以看到...
