### ISSUE TITLE
跟MJRefresh 有崩溃冲突 ！！！！！

### ISSUE THREAD

**Issue by LeeWongSnail** [chenfanfang/AvoidCrash#69]
CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:] + 452
-- | --
2 UXLive | -[NSMutableDictionary(AvoidCrash) avoidCrashSetObject:forKeyedSubscript:] (NSMutableDictionary+AvoidCrash.m:71)
3 UXLive | -[MJProperty setPorpertyKeys:forClass:] (MJProperty.m:153)
4 UXLive | -[MJProperty setOriginKey:forClass:] (MJProperty.m:133)
5 UXLive | __32+[NSObject(Property) properties]_block_invoke (NSObject+MJProperty.m:169)
6 UXLive | +[NSObject(MJClass) mj_enumerateClasses:] (NSObject+MJClass.m:63)
7 UXLive | +[NSObject(Property) properties] (NSObject+MJProperty.m:178)
8 UXLive | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:0)
9 UXLive | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:197)
10 UXLive | +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:218)
11 UXLive | __48-[NSObject(MJKeyValue) mj_setKeyValues:context:]_block_invoke (NSObject+MJKeyValue.m:0)
12 UXLive | +[NSObject(Property) mj_enumerateProperties:] (NSObject+MJProperty.m:146)
13 UXLive | -[NSObject(MJKeyValue) mj_setKeyValues:context:] (NSObject+MJKeyValue.m:197)
14 UXLive | +[NSObject(MJKeyValue) mj_objectWithKeyValues:context:] (NSObject+MJKeyValue.m:218)
15 UXLive | +[NSObject(MJKeyValue) mj_objectArrayWithKeyValuesArray:context:] (NSObject+MJKeyValue.m:0)

**Comment by kobe1941** [comment]
你的日志看不到具体的错误信息，
试试这个https://github.com/kobe1941/FFExtension
